#Site settings
title: A.M.P.A. Marcos Frechín
remote_theme: ampamarcosfrechin/feeling-responsive
permalink: pretty

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
shortname: ampamarcosfrechin

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

livereload: true

google_analytics: UA-149878673-2

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
      hero_image: /img/header.jpg
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Sergio Castillo"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true
theme: jekyll-theme-tactile