- menu_name: "Servicios"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Feed RSS"

- name: "Atom"
  url: "/atom.xml"
  title: "Feed Atom"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap para Google Webmaster Tools"
